"""create tables

Revision ID: 3c6d0bcc6fcb
Revises: f82be414f7df
Create Date: 2025-09-29 16:47:43.972487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c6d0bcc6fcb'
down_revision = 'f82be414f7df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
