"""create tables

Revision ID: d173ce22db67
Revises: 3c6d0bcc6fcb
Create Date: 2025-09-29 17:00:17.128574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd173ce22db67'
down_revision = '3c6d0bcc6fcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Book',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('isbn', sa.String(), nullable=True),
    sa.Column('copies_available', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('isbn')
    )
    op.create_table('Library',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('Member',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('BorrowRecord',
    sa.Column('Id', sa.UUID(), nullable=False),
    sa.Column('book_id', sa.UUID(), nullable=True),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('library_id', sa.UUID(), nullable=True),
    sa.Column('borrowed_at', sa.DateTime(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('returned_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('borrowed', 'returned', 'overdue', name='borrowstatus'), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['Book.Id'], ),
    sa.ForeignKeyConstraint(['library_id'], ['Library.Id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['Member.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('BorrowRecord')
    op.drop_table('Member')
    op.drop_table('Library')
    op.drop_table('Book')
    # ### end Alembic commands ###
