"""create tables

Revision ID: f82be414f7df
Revises: 3ef12cd072ea
Create Date: 2025-09-29 16:42:26.667200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f82be414f7df'
down_revision = '3ef12cd072ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
